name = "cms-sekolah"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "SESSION"
id = "5671c9908ce441a489126cfc946596bd"

